server:
  port: 5000
spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: "validate"
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/pizzeriaOrders?createDatabaseIfNotExist=true"
    username: "root"
    password: "VaxiDrez2005$"
spring-doc:
  model-converters:
    pageable-converter:
      enabled: true
  override-with-generic-response: true
  use-fqn: true
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    operationsSorter: "method"
    tryItOutEnabled: false
    filter: true
    syntaxHighlight:
      activated: true
  api-docs:
    path: "/api-docs"